version: "3"
services:
  database:
    image: mysql:5.7
    restart: always
    # SET: Work directory
    working_dir: /opt/app/vtimeline/database/
    # SET: Envirement variables
    environment:
      # Database AUTH
      MYSQL_DATABASE: "vtimeline_development"
      MYSQL_USER: "app"
      MYSQL_PASSWORD: "iforgot"
      MYSQL_ROOT_PASSWORD: "root"
    # MAP: Ports
    ports:
      - "3306:3306"
    # EXPOSE: Ports
    expose:
      - "3306"
    # DEFINE: Shared volumes
    volumes:
      - ./:/opt/app/vtimeline/database/
      - /opt/docker/mysql/vtimeline:/var/lib/mysql
